PROJECT:=SpinalSulfur

TOP:=TopLevel

include magicleda/magicleda.mk

SRCS_XDC_EXTRA:=${LEDA_XDC}
SRCS_SPINAL_EXTRA:=${LEDA_SPINAL}
PLATFORM:=${LEDA_PLATFORM}
FLASH:=${LEDA_FLASH}

include makefile-spinal/makefile-spinal.mk
